Repository milieuinfo/webcomponent-vl-ui-pattern, pull requests merged in 2020-07, with the labels that each got.

#1 Initiële code
  dist/vl-pattern.js
  dist/vl-pattern.min.js
  dist/vl-pattern.src.js
  package-lock.json
  package.json
  src/vl-pattern.js
  test/e2e/pattern.test.js
Labels: enhancement

#5 Update dependency vl-ui-core to v5.6.0
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#6 Update vl-ui-core
  package-lock.json
  package.json
  src/vl-pattern.js
Labels: chore

#7 Update vl-ui-core
  package-lock.json
  package.json
  src/vl-pattern.js
Labels: chore

#8 Update dependency vl-ui-core to v5.6.2
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#9 Update dependencies
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
Labels: chore
